services:
  - type: web
    name: document-theme-identifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1